version: '3.8'

services:
  spring-app:
    image: your-spring-boot-app:latest
    container_name: spring-app
    ports:
      - "8080:8080"
    environment:
      - IPFS_URL=http://ipfs-node:5001
    depends_on:
      - ipfs-node
    networks:
      - app-network

  ipfs-node:
    image: ipfs/go-ipfs:latest
    container_name: ipfs-node
    ports:
      - "4001:4001"
      - "5001:5001"
      - "8080:8080"
    volumes:
      - ipfs-data:/data/ipfs
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  ipfs-data: